"""
title: Pydantic models for medical-LLM responses.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from hiperhealth.llm import _clean_json_text


class LLMDiagnosis(BaseModel):
    """
    title: Schema produced by /diagnosis and /exams endpoints.
    attributes:
      summary:
        type: str
        description: Value for summary.
      options:
        type: list[str] | dict[str, float]
        description: Value for options.
    """

    summary: str = Field(..., max_length=800)
    options: list[str] | dict[str, float]

    @classmethod
    def from_llm(cls, text: str) -> 'LLMDiagnosis':
        """
        title: Parse a JSON string generated by our medical LLM.
        parameters:
          text:
            type: str
            description: Value for text.
        returns:
          type: LLMDiagnosis
          description: Return value.
        """
        return cls.model_validate_json(_clean_json_text(text))


class LLMInquiryItem(BaseModel):
    """
    title: A single piece of information the LLM identifies as missing.
    summary: |-
      Does not include skill_name or stage — those are added by the
      calling skill after filtering.
    attributes:
      field:
        type: str
        description: Machine-readable key, e.g. "smoking_history".
      label:
        type: str
        description: Human-readable label, e.g. "Smoking History".
      description:
        type: str
        description: Why this information is needed.
      priority:
        type: Literal[required, supplementary, deferred]
      input_type:
        type: str
        description: Expected input widget (text, select, number, boolean).
      choices:
        type: list[str] | None
        description: Valid options when input_type is "select".
    """

    field: str
    label: str
    description: str = ''
    priority: Literal['required', 'supplementary', 'deferred'] = (
        'supplementary'
    )
    input_type: str = 'text'
    choices: list[str] | None = None


class LLMInquiryList(BaseModel):
    """
    title: LLM response listing missing clinical information.
    attributes:
      inquiries:
        type: list[LLMInquiryItem]
    """

    inquiries: list[LLMInquiryItem]


__all__ = ['LLMDiagnosis', 'LLMInquiryItem', 'LLMInquiryList']
