"""
title: Pydantic models for medical-LLM responses.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from hiperhealth.llm import _clean_json_text


class LLMDiagnosis(BaseModel):
    """
    title: Schema produced by /diagnosis and /exams endpoints.
    attributes:
      summary:
        type: str
        description: Value for summary.
      options:
        type: list[str] | dict[str, float]
        description: Value for options.
    """

    summary: str = Field(..., max_length=800)
    options: list[str] | dict[str, float]

    @classmethod
    def from_llm(cls, text: str) -> 'LLMDiagnosis':
        """
        title: Parse a JSON string generated by our medical LLM.
        parameters:
          text:
            type: str
            description: Value for text.
        returns:
          type: LLMDiagnosis
          description: Return value.
        """
        return cls.model_validate_json(_clean_json_text(text))


__all__ = ['LLMDiagnosis']
