"""
title: Autogenerated ORM models from Pydantic schemas.
summary: DO NOT EDIT MANUALLY. Regenerate via `python generate_orm_models.py`.
"""

from __future__ import annotations

import uuid

from datetime import datetime
from typing import Any, Literal, Optional, Union  # noqa

from public import public
from sqlalchemy import (
    JSON,
    DateTime,
    Integer,
    String,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


@public
class Base(DeclarativeBase):
    """
    title: Declarative base for  HiPerHealth.
    """

    pass


@public
@public
class LLMDiagnosis(Base):
    """
    title: LLMDiagnosis autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      summary:
        type: Mapped[str]
        description: Value for summary.
      options:
        type: Mapped[Any]
        description: Value for options.
    """

    __tablename__ = 'llmdiagnosis'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    summary: Mapped[str] = mapped_column(String, index=True, default=...)
    options: Mapped[Any] = mapped_column(JSON, index=True, default=...)


@public
@public
class Annotation(Base):
    """
    title: Annotation autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      authorReference:
        type: Mapped[Any]
        description: Value for authorReference.
      authorString:
        type: Mapped[Any]
        description: Value for authorString.
      authorString__ext:
        type: Mapped[Any]
        description: Value for authorString__ext.
      text:
        type: Mapped[Any]
        description: Value for text.
      text__ext:
        type: Mapped[Any]
        description: Value for text__ext.
      time:
        type: Mapped[Any]
        description: Value for time.
      time__ext:
        type: Mapped[Any]
        description: Value for time__ext.
    """

    __tablename__ = 'annotation'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    authorReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    authorString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    authorString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    time: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    time__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class ClinicalImpression(Base):
    """
    title: ClinicalImpression autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      implicitRules:
        type: Mapped[Any]
        description: Value for implicitRules.
      implicitRules__ext:
        type: Mapped[Any]
        description: Value for implicitRules__ext.
      language__ext:
        type: Mapped[Any]
        description: Value for language__ext.
      meta:
        type: Mapped[Any]
        description: Value for meta.
      contained:
        type: Mapped[Any]
        description: Value for contained.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      modifierExtension:
        type: Mapped[Any]
        description: Value for modifierExtension.
      text:
        type: Mapped[Any]
        description: Value for text.
      changePattern:
        type: Mapped[Any]
        description: Value for changePattern.
      date:
        type: Mapped[Any]
        description: Value for date.
      date__ext:
        type: Mapped[Any]
        description: Value for date__ext.
      description:
        type: Mapped[Any]
        description: Value for description.
      description__ext:
        type: Mapped[Any]
        description: Value for description__ext.
      effectiveDateTime:
        type: Mapped[Any]
        description: Value for effectiveDateTime.
      effectiveDateTime__ext:
        type: Mapped[Any]
        description: Value for effectiveDateTime__ext.
      effectivePeriod:
        type: Mapped[Any]
        description: Value for effectivePeriod.
      encounter:
        type: Mapped[Any]
        description: Value for encounter.
      finding:
        type: Mapped[Any]
        description: Value for finding.
      identifier:
        type: Mapped[Any]
        description: Value for identifier.
      note:
        type: Mapped[Any]
        description: Value for note.
      performer:
        type: Mapped[Any]
        description: Value for performer.
      previous:
        type: Mapped[Any]
        description: Value for previous.
      problem:
        type: Mapped[Any]
        description: Value for problem.
      prognosisCodeableConcept:
        type: Mapped[Any]
        description: Value for prognosisCodeableConcept.
      prognosisReference:
        type: Mapped[Any]
        description: Value for prognosisReference.
      protocol:
        type: Mapped[Any]
        description: Value for protocol.
      protocol__ext:
        type: Mapped[Any]
        description: Value for protocol__ext.
      status:
        type: Mapped[Any]
        description: Value for status.
      status__ext:
        type: Mapped[Any]
        description: Value for status__ext.
      statusReason:
        type: Mapped[Any]
        description: Value for statusReason.
      subject:
        type: Mapped[Any]
        description: Value for subject.
      summary:
        type: Mapped[Any]
        description: Value for summary.
      summary__ext:
        type: Mapped[Any]
        description: Value for summary__ext.
      supportingInfo:
        type: Mapped[Any]
        description: Value for supportingInfo.
    """

    __tablename__ = 'clinicalimpression'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    language__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    meta: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contained: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    changePattern: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    date: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    date__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    description: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    description__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectivePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    encounter: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    finding: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    identifier: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    note: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    performer: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    previous: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    problem: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    prognosisCodeableConcept: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    prognosisReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    protocol: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    protocol__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    statusReason: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    subject: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    summary: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    summary__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    supportingInfo: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class Condition(Base):
    """
    title: Condition autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      implicitRules:
        type: Mapped[Any]
        description: Value for implicitRules.
      implicitRules__ext:
        type: Mapped[Any]
        description: Value for implicitRules__ext.
      language__ext:
        type: Mapped[Any]
        description: Value for language__ext.
      meta:
        type: Mapped[Any]
        description: Value for meta.
      contained:
        type: Mapped[Any]
        description: Value for contained.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      modifierExtension:
        type: Mapped[Any]
        description: Value for modifierExtension.
      text:
        type: Mapped[Any]
        description: Value for text.
      abatementAge:
        type: Mapped[Any]
        description: Value for abatementAge.
      abatementDateTime:
        type: Mapped[Any]
        description: Value for abatementDateTime.
      abatementDateTime__ext:
        type: Mapped[Any]
        description: Value for abatementDateTime__ext.
      abatementPeriod:
        type: Mapped[Any]
        description: Value for abatementPeriod.
      abatementRange:
        type: Mapped[Any]
        description: Value for abatementRange.
      abatementString:
        type: Mapped[Any]
        description: Value for abatementString.
      abatementString__ext:
        type: Mapped[Any]
        description: Value for abatementString__ext.
      bodySite:
        type: Mapped[Any]
        description: Value for bodySite.
      category:
        type: Mapped[Any]
        description: Value for category.
      clinicalStatus:
        type: Mapped[Any]
        description: Value for clinicalStatus.
      code:
        type: Mapped[Any]
        description: Value for code.
      encounter:
        type: Mapped[Any]
        description: Value for encounter.
      evidence:
        type: Mapped[Any]
        description: Value for evidence.
      identifier:
        type: Mapped[Any]
        description: Value for identifier.
      note:
        type: Mapped[Any]
        description: Value for note.
      onsetAge:
        type: Mapped[Any]
        description: Value for onsetAge.
      onsetDateTime:
        type: Mapped[Any]
        description: Value for onsetDateTime.
      onsetDateTime__ext:
        type: Mapped[Any]
        description: Value for onsetDateTime__ext.
      onsetPeriod:
        type: Mapped[Any]
        description: Value for onsetPeriod.
      onsetRange:
        type: Mapped[Any]
        description: Value for onsetRange.
      onsetString:
        type: Mapped[Any]
        description: Value for onsetString.
      onsetString__ext:
        type: Mapped[Any]
        description: Value for onsetString__ext.
      participant:
        type: Mapped[Any]
        description: Value for participant.
      recordedDate:
        type: Mapped[Any]
        description: Value for recordedDate.
      recordedDate__ext:
        type: Mapped[Any]
        description: Value for recordedDate__ext.
      severity:
        type: Mapped[Any]
        description: Value for severity.
      stage:
        type: Mapped[Any]
        description: Value for stage.
      subject:
        type: Mapped[Any]
        description: Value for subject.
      verificationStatus:
        type: Mapped[Any]
        description: Value for verificationStatus.
    """

    __tablename__ = 'condition'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    language__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    meta: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contained: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementAge: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementPeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    abatementString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    bodySite: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    category: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    clinicalStatus: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    code: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    encounter: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    evidence: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    identifier: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    note: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetAge: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetPeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    onsetString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    participant: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    recordedDate: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    recordedDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    severity: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    stage: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    subject: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    verificationStatus: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class Encounter(Base):
    """
    title: Encounter autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      implicitRules:
        type: Mapped[Any]
        description: Value for implicitRules.
      implicitRules__ext:
        type: Mapped[Any]
        description: Value for implicitRules__ext.
      language__ext:
        type: Mapped[Any]
        description: Value for language__ext.
      meta:
        type: Mapped[Any]
        description: Value for meta.
      contained:
        type: Mapped[Any]
        description: Value for contained.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      modifierExtension:
        type: Mapped[Any]
        description: Value for modifierExtension.
      text:
        type: Mapped[Any]
        description: Value for text.
      account:
        type: Mapped[Any]
        description: Value for account.
      actualPeriod:
        type: Mapped[Any]
        description: Value for actualPeriod.
      admission:
        type: Mapped[Any]
        description: Value for admission.
      appointment:
        type: Mapped[Any]
        description: Value for appointment.
      basedOn:
        type: Mapped[Any]
        description: Value for basedOn.
      careTeam:
        type: Mapped[Any]
        description: Value for careTeam.
      class_fhir:
        type: Mapped[Any]
        description: Value for class_fhir.
      diagnosis:
        type: Mapped[Any]
        description: Value for diagnosis.
      dietPreference:
        type: Mapped[Any]
        description: Value for dietPreference.
      episodeOfCare:
        type: Mapped[Any]
        description: Value for episodeOfCare.
      identifier:
        type: Mapped[Any]
        description: Value for identifier.
      length:
        type: Mapped[Any]
        description: Value for length.
      location:
        type: Mapped[Any]
        description: Value for location.
      partOf:
        type: Mapped[Any]
        description: Value for partOf.
      participant:
        type: Mapped[Any]
        description: Value for participant.
      plannedEndDate:
        type: Mapped[Any]
        description: Value for plannedEndDate.
      plannedEndDate__ext:
        type: Mapped[Any]
        description: Value for plannedEndDate__ext.
      plannedStartDate:
        type: Mapped[Any]
        description: Value for plannedStartDate.
      plannedStartDate__ext:
        type: Mapped[Any]
        description: Value for plannedStartDate__ext.
      priority:
        type: Mapped[Any]
        description: Value for priority.
      reason:
        type: Mapped[Any]
        description: Value for reason.
      serviceProvider:
        type: Mapped[Any]
        description: Value for serviceProvider.
      serviceType:
        type: Mapped[Any]
        description: Value for serviceType.
      specialArrangement:
        type: Mapped[Any]
        description: Value for specialArrangement.
      specialCourtesy:
        type: Mapped[Any]
        description: Value for specialCourtesy.
      status:
        type: Mapped[Any]
        description: Value for status.
      status__ext:
        type: Mapped[Any]
        description: Value for status__ext.
      subject:
        type: Mapped[Any]
        description: Value for subject.
      subjectStatus:
        type: Mapped[Any]
        description: Value for subjectStatus.
      type:
        type: Mapped[Any]
        description: Value for type.
      virtualService:
        type: Mapped[Any]
        description: Value for virtualService.
      canonicalEpisodeId:
        type: Mapped[Any]
        description: Value for canonicalEpisodeId.
    """

    __tablename__ = 'encounter'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    language__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    meta: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contained: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    account: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    actualPeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    admission: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    appointment: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    basedOn: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    careTeam: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    class_fhir: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    diagnosis: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    dietPreference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    episodeOfCare: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    identifier: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    length: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    location: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    partOf: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    participant: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    plannedEndDate: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    plannedEndDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    plannedStartDate: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    plannedStartDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    priority: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    reason: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    serviceProvider: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    serviceType: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    specialArrangement: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    specialCourtesy: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    subject: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    subjectStatus: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    type: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    virtualService: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    canonicalEpisodeId: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class Observation(Base):
    """
    title: Observation autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      implicitRules:
        type: Mapped[Any]
        description: Value for implicitRules.
      implicitRules__ext:
        type: Mapped[Any]
        description: Value for implicitRules__ext.
      language__ext:
        type: Mapped[Any]
        description: Value for language__ext.
      meta:
        type: Mapped[Any]
        description: Value for meta.
      contained:
        type: Mapped[Any]
        description: Value for contained.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      modifierExtension:
        type: Mapped[Any]
        description: Value for modifierExtension.
      text:
        type: Mapped[Any]
        description: Value for text.
      basedOn:
        type: Mapped[Any]
        description: Value for basedOn.
      bodySite:
        type: Mapped[Any]
        description: Value for bodySite.
      bodyStructure:
        type: Mapped[Any]
        description: Value for bodyStructure.
      category:
        type: Mapped[Any]
        description: Value for category.
      code:
        type: Mapped[Any]
        description: Value for code.
      component:
        type: Mapped[Any]
        description: Value for component.
      dataAbsentReason:
        type: Mapped[Any]
        description: Value for dataAbsentReason.
      derivedFrom:
        type: Mapped[Any]
        description: Value for derivedFrom.
      device:
        type: Mapped[Any]
        description: Value for device.
      effectiveDateTime:
        type: Mapped[Any]
        description: Value for effectiveDateTime.
      effectiveDateTime__ext:
        type: Mapped[Any]
        description: Value for effectiveDateTime__ext.
      effectiveInstant:
        type: Mapped[Any]
        description: Value for effectiveInstant.
      effectiveInstant__ext:
        type: Mapped[Any]
        description: Value for effectiveInstant__ext.
      effectivePeriod:
        type: Mapped[Any]
        description: Value for effectivePeriod.
      effectiveTiming:
        type: Mapped[Any]
        description: Value for effectiveTiming.
      encounter:
        type: Mapped[Any]
        description: Value for encounter.
      focus:
        type: Mapped[Any]
        description: Value for focus.
      hasMember:
        type: Mapped[Any]
        description: Value for hasMember.
      identifier:
        type: Mapped[Any]
        description: Value for identifier.
      instantiatesCanonical:
        type: Mapped[Any]
        description: Value for instantiatesCanonical.
      instantiatesCanonical__ext:
        type: Mapped[Any]
        description: Value for instantiatesCanonical__ext.
      instantiatesReference:
        type: Mapped[Any]
        description: Value for instantiatesReference.
      interpretation:
        type: Mapped[Any]
        description: Value for interpretation.
      issued:
        type: Mapped[Any]
        description: Value for issued.
      issued__ext:
        type: Mapped[Any]
        description: Value for issued__ext.
      method:
        type: Mapped[Any]
        description: Value for method.
      note:
        type: Mapped[Any]
        description: Value for note.
      partOf:
        type: Mapped[Any]
        description: Value for partOf.
      performer:
        type: Mapped[Any]
        description: Value for performer.
      referenceRange:
        type: Mapped[Any]
        description: Value for referenceRange.
      specimen:
        type: Mapped[Any]
        description: Value for specimen.
      status:
        type: Mapped[Any]
        description: Value for status.
      status__ext:
        type: Mapped[Any]
        description: Value for status__ext.
      subject:
        type: Mapped[Any]
        description: Value for subject.
      triggeredBy:
        type: Mapped[Any]
        description: Value for triggeredBy.
      valueAttachment:
        type: Mapped[Any]
        description: Value for valueAttachment.
      valueBoolean:
        type: Mapped[Any]
        description: Value for valueBoolean.
      valueBoolean__ext:
        type: Mapped[Any]
        description: Value for valueBoolean__ext.
      valueCodeableConcept:
        type: Mapped[Any]
        description: Value for valueCodeableConcept.
      valueDateTime:
        type: Mapped[Any]
        description: Value for valueDateTime.
      valueDateTime__ext:
        type: Mapped[Any]
        description: Value for valueDateTime__ext.
      valueInteger:
        type: Mapped[Any]
        description: Value for valueInteger.
      valueInteger__ext:
        type: Mapped[Any]
        description: Value for valueInteger__ext.
      valuePeriod:
        type: Mapped[Any]
        description: Value for valuePeriod.
      valueQuantity:
        type: Mapped[Any]
        description: Value for valueQuantity.
      valueRange:
        type: Mapped[Any]
        description: Value for valueRange.
      valueRatio:
        type: Mapped[Any]
        description: Value for valueRatio.
      valueReference:
        type: Mapped[Any]
        description: Value for valueReference.
      valueSampledData:
        type: Mapped[Any]
        description: Value for valueSampledData.
      valueString:
        type: Mapped[Any]
        description: Value for valueString.
      valueString__ext:
        type: Mapped[Any]
        description: Value for valueString__ext.
      valueTime:
        type: Mapped[Any]
        description: Value for valueTime.
      valueTime__ext:
        type: Mapped[Any]
        description: Value for valueTime__ext.
    """

    __tablename__ = 'observation'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    language__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    meta: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contained: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    basedOn: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    bodySite: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    bodyStructure: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    category: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    code: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    component: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    dataAbsentReason: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    derivedFrom: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    device: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveInstant: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveInstant__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectivePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    effectiveTiming: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    encounter: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    focus: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    hasMember: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    identifier: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesCanonical: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesCanonical__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    interpretation: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    issued: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    issued__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    method: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    note: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    partOf: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    performer: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    referenceRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    specimen: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    subject: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    triggeredBy: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueAttachment: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueCodeableConcept: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueInteger: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueInteger__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valuePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueQuantity: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueRatio: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueSampledData: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    valueTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class Patient(Base):
    """
    title: Patient autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      implicitRules:
        type: Mapped[Any]
        description: Value for implicitRules.
      implicitRules__ext:
        type: Mapped[Any]
        description: Value for implicitRules__ext.
      language__ext:
        type: Mapped[Any]
        description: Value for language__ext.
      meta:
        type: Mapped[Any]
        description: Value for meta.
      contained:
        type: Mapped[Any]
        description: Value for contained.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      modifierExtension:
        type: Mapped[Any]
        description: Value for modifierExtension.
      text:
        type: Mapped[Any]
        description: Value for text.
      active:
        type: Mapped[Any]
        description: Value for active.
      active__ext:
        type: Mapped[Any]
        description: Value for active__ext.
      address:
        type: Mapped[Any]
        description: Value for address.
      birthDate:
        type: Mapped[Any]
        description: Value for birthDate.
      birthDate__ext:
        type: Mapped[Any]
        description: Value for birthDate__ext.
      communication:
        type: Mapped[Any]
        description: Value for communication.
      contact:
        type: Mapped[Any]
        description: Value for contact.
      deceasedBoolean:
        type: Mapped[Any]
        description: Value for deceasedBoolean.
      deceasedBoolean__ext:
        type: Mapped[Any]
        description: Value for deceasedBoolean__ext.
      deceasedDateTime:
        type: Mapped[Any]
        description: Value for deceasedDateTime.
      deceasedDateTime__ext:
        type: Mapped[Any]
        description: Value for deceasedDateTime__ext.
      gender:
        type: Mapped[Any]
        description: Value for gender.
      gender__ext:
        type: Mapped[Any]
        description: Value for gender__ext.
      generalPractitioner:
        type: Mapped[Any]
        description: Value for generalPractitioner.
      identifier:
        type: Mapped[Any]
        description: Value for identifier.
      link:
        type: Mapped[Any]
        description: Value for link.
      managingOrganization:
        type: Mapped[Any]
        description: Value for managingOrganization.
      maritalStatus:
        type: Mapped[Any]
        description: Value for maritalStatus.
      multipleBirthBoolean:
        type: Mapped[Any]
        description: Value for multipleBirthBoolean.
      multipleBirthBoolean__ext:
        type: Mapped[Any]
        description: Value for multipleBirthBoolean__ext.
      multipleBirthInteger:
        type: Mapped[Any]
        description: Value for multipleBirthInteger.
      multipleBirthInteger__ext:
        type: Mapped[Any]
        description: Value for multipleBirthInteger__ext.
      name:
        type: Mapped[Any]
        description: Value for name.
      photo:
        type: Mapped[Any]
        description: Value for photo.
      telecom:
        type: Mapped[Any]
        description: Value for telecom.
    """

    __tablename__ = 'patient'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    language__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    meta: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contained: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    active: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    active__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    address: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    birthDate: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    birthDate__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    communication: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contact: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    deceasedBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    deceasedBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    deceasedDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    deceasedDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    gender: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    gender__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    generalPractitioner: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    identifier: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    link: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    managingOrganization: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    maritalStatus: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    multipleBirthBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    multipleBirthBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    multipleBirthInteger: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    multipleBirthInteger__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    name: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    photo: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    telecom: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class Procedure(Base):
    """
    title: Procedure autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      fhir_comments:
        type: Mapped[Any]
        description: Value for fhir_comments.
      implicitRules:
        type: Mapped[Any]
        description: Value for implicitRules.
      implicitRules__ext:
        type: Mapped[Any]
        description: Value for implicitRules__ext.
      language__ext:
        type: Mapped[Any]
        description: Value for language__ext.
      meta:
        type: Mapped[Any]
        description: Value for meta.
      contained:
        type: Mapped[Any]
        description: Value for contained.
      extension:
        type: Mapped[Any]
        description: Value for extension.
      modifierExtension:
        type: Mapped[Any]
        description: Value for modifierExtension.
      text:
        type: Mapped[Any]
        description: Value for text.
      basedOn:
        type: Mapped[Any]
        description: Value for basedOn.
      bodySite:
        type: Mapped[Any]
        description: Value for bodySite.
      category:
        type: Mapped[Any]
        description: Value for category.
      code:
        type: Mapped[Any]
        description: Value for code.
      complication:
        type: Mapped[Any]
        description: Value for complication.
      encounter:
        type: Mapped[Any]
        description: Value for encounter.
      focalDevice:
        type: Mapped[Any]
        description: Value for focalDevice.
      focus:
        type: Mapped[Any]
        description: Value for focus.
      followUp:
        type: Mapped[Any]
        description: Value for followUp.
      identifier:
        type: Mapped[Any]
        description: Value for identifier.
      instantiatesCanonical:
        type: Mapped[Any]
        description: Value for instantiatesCanonical.
      instantiatesCanonical__ext:
        type: Mapped[Any]
        description: Value for instantiatesCanonical__ext.
      instantiatesUri:
        type: Mapped[Any]
        description: Value for instantiatesUri.
      instantiatesUri__ext:
        type: Mapped[Any]
        description: Value for instantiatesUri__ext.
      location:
        type: Mapped[Any]
        description: Value for location.
      note:
        type: Mapped[Any]
        description: Value for note.
      occurrenceAge:
        type: Mapped[Any]
        description: Value for occurrenceAge.
      occurrenceDateTime:
        type: Mapped[Any]
        description: Value for occurrenceDateTime.
      occurrenceDateTime__ext:
        type: Mapped[Any]
        description: Value for occurrenceDateTime__ext.
      occurrencePeriod:
        type: Mapped[Any]
        description: Value for occurrencePeriod.
      occurrenceRange:
        type: Mapped[Any]
        description: Value for occurrenceRange.
      occurrenceString:
        type: Mapped[Any]
        description: Value for occurrenceString.
      occurrenceString__ext:
        type: Mapped[Any]
        description: Value for occurrenceString__ext.
      occurrenceTiming:
        type: Mapped[Any]
        description: Value for occurrenceTiming.
      outcome:
        type: Mapped[Any]
        description: Value for outcome.
      partOf:
        type: Mapped[Any]
        description: Value for partOf.
      performer:
        type: Mapped[Any]
        description: Value for performer.
      reason:
        type: Mapped[Any]
        description: Value for reason.
      recorded:
        type: Mapped[Any]
        description: Value for recorded.
      recorded__ext:
        type: Mapped[Any]
        description: Value for recorded__ext.
      recorder:
        type: Mapped[Any]
        description: Value for recorder.
      report:
        type: Mapped[Any]
        description: Value for report.
      reportedBoolean:
        type: Mapped[Any]
        description: Value for reportedBoolean.
      reportedBoolean__ext:
        type: Mapped[Any]
        description: Value for reportedBoolean__ext.
      reportedReference:
        type: Mapped[Any]
        description: Value for reportedReference.
      status:
        type: Mapped[Any]
        description: Value for status.
      status__ext:
        type: Mapped[Any]
        description: Value for status__ext.
      statusReason:
        type: Mapped[Any]
        description: Value for statusReason.
      subject:
        type: Mapped[Any]
        description: Value for subject.
      supportingInfo:
        type: Mapped[Any]
        description: Value for supportingInfo.
      used:
        type: Mapped[Any]
        description: Value for used.
    """

    __tablename__ = 'procedure'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    fhir_comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    implicitRules__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    language__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    meta: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    contained: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    extension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    modifierExtension: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    text: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    basedOn: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    bodySite: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    category: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    code: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    complication: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    encounter: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    focalDevice: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    focus: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    followUp: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    identifier: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesCanonical: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesCanonical__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesUri: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    instantiatesUri__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    location: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    note: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceAge: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceDateTime: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceDateTime__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrencePeriod: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceRange: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceString: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceString__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    occurrenceTiming: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    outcome: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    partOf: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    performer: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    reason: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    recorded: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    recorded__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    recorder: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    report: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    reportedBoolean: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    reportedBoolean__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    reportedReference: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    status__ext: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    statusReason: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    subject: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    supportingInfo: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    used: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class AIOutput(Base):
    """
    title: AIOutput autogenerated.
    attributes:
      language:
        type: Mapped[Any]
        description: Value for language.
      id:
        type: Mapped[str]
        description: Value for id.
      encounter_id:
        type: Mapped[str]
        description: Value for encounter_id.
      type:
        type: Mapped[Any]
        description: Value for type.
      content:
        type: Mapped[str]
        description: Value for content.
      model_version:
        type: Mapped[str]
        description: Value for model_version.
      timestamp:
        type: Mapped[datetime]
        description: Value for timestamp.
    """

    __tablename__ = 'aioutput'

    language: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    id: Mapped[str] = mapped_column(String, primary_key=True)
    encounter_id: Mapped[str] = mapped_column(String, index=True, default=...)
    type: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    content: Mapped[str] = mapped_column(String, index=True, default=...)
    model_version: Mapped[str] = mapped_column(String, index=True, default=...)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime, index=True, default=...
    )


@public
@public
class DeIdentifiedDatasetDescriptor(Base):
    """
    title: DeIdentifiedDatasetDescriptor autogenerated.
    attributes:
      id:
        type: Mapped[str]
        description: Value for id.
      language:
        type: Mapped[Any]
        description: Value for language.
      dataset_id:
        type: Mapped[str]
        description: Value for dataset_id.
      generation_date:
        type: Mapped[datetime]
        description: Value for generation_date.
      version:
        type: Mapped[str]
        description: Value for version.
      records:
        type: Mapped[int]
        description: Value for records.
      license:
        type: Mapped[str]
        description: Value for license.
      url:
        type: Mapped[Any]
        description: Value for url.
    """

    __tablename__ = 'deidentifieddatasetdescriptor'

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    language: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    dataset_id: Mapped[str] = mapped_column(String, index=True, default=...)
    generation_date: Mapped[datetime] = mapped_column(
        DateTime, index=True, default=...
    )
    version: Mapped[str] = mapped_column(String, index=True, default=...)
    records: Mapped[int] = mapped_column(Integer, index=True, default=...)
    license: Mapped[str] = mapped_column(String, index=True, default=...)
    url: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )


@public
@public
class Evaluation(Base):
    """
    title: Evaluation autogenerated.
    attributes:
      language:
        type: Mapped[Any]
        description: Value for language.
      id:
        type: Mapped[str]
        description: Value for id.
      aioutput_id:
        type: Mapped[str]
        description: Value for aioutput_id.
      output_type:
        type: Mapped[Any]
        description: Value for output_type.
      ratings:
        type: Mapped[Any]
        description: Value for ratings.
      safety:
        type: Mapped[Any]
        description: Value for safety.
      comments:
        type: Mapped[Any]
        description: Value for comments.
      timestamp:
        type: Mapped[datetime]
        description: Value for timestamp.
    """

    __tablename__ = 'evaluation'

    language: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    id: Mapped[str] = mapped_column(String, primary_key=True)
    aioutput_id: Mapped[str] = mapped_column(String, index=True, default=...)
    output_type: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    ratings: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    safety: Mapped[Any] = mapped_column(JSON, index=True, default=...)
    comments: Mapped[Any] = mapped_column(
        JSON, nullable=True, index=True, default=None
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime, index=True, default=...
    )
